import type { RemoteGitHubConfig } from './remoteConfig.ts';

export function readmeResourceText(github: RemoteGitHubConfig): string {
  return [
    'Centera Guidance MCP (Remote)',
    '',
    `Source: github:${github.owner}/${github.repo} (ref: ${github.ref})`,
    'Endpoint: /api/mcp',
    '',
    'Tools:',
    '- centera_list_dir',
    '- centera_read_file',
    '- centera_search',
    '- centera_guardrails_check',
    '- centera_describe_architecture',
    '- centera_list_instruction_files',
    '- centera_get_instruction_tree',
    '- centera_get_effective_instructions',
    '- centera_bootstrap',
    '',
    'Resources:',
    '- centera://docs/agents',
    '- centera://docs/claude',
    '- centera://docs/openspec/agents',
    '- centera://docs/openspec/project',
    '- centera://docs/repo/readme',
    '- centera://docs/codex/instructions',
    '- centera://docs/ai/trust-policy',
    '- centera://docs/openapi',
    '- centera://docs/backend/db/agents',
    '- centera://docs/backend/db/readme',
    '- centera://docs/backend/db/docker-compose',
    '- centera://docs/backend/db/env-example',
    '- centera://docs/frontend/detail-layout',
    '- centera://docs/frontend/save-actions',
    '- centera://docs/frontend/error-alert',
    '- centera://docs/frontend/loading-button',
    '- centera://docs/frontend/ui-tokens',
    '- centera://docs/frontend/theme-constants',
    '- centera://docs/frontend/i18n',
    '- centera://docs/frontend/api/client',
    '- centera://docs/frontend/api/errors',
    '- centera://docs/frontend/auth/permissions',
    '- centera://docs/frontend/test/test-utils',
    '- centera://docs/frontend/shared/data-table',
    '- centera://docs/frontend/shared/form-dialog',
    '- centera://docs/frontend/shared/data-state',
    '- centera://docs/frontend/shared/action-button',
    '- centera://docs/backend/rest-exception-handler',
    '- centera://docs/backend/api-delegate-impl-example',
  ].join('\n');
}
